# Generated by Django 4.2.4 on 2024-09-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('report_type', models.CharField(choices=[('public', 'Public Share'), ('police', 'Police Report')], max_length=20)),
                ('public_share_level', models.CharField(blank=True, max_length=20, null=True)),
                ('police_station', models.CharField(blank=True, max_length=255, null=True)),
                ('case_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
