# Generated by Django 4.2.4 on 2024-09-04 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0002_incidentreport_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='media',
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='public_share_level',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('community', 'Community')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='report_type',
            field=models.CharField(choices=[('public', 'Public Share'), ('police', 'Police Report')], max_length=50),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='incidentreport.incidentreport')),
            ],
        ),
    ]
