# Generated by Django 4.2.4 on 2024-09-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0003_remove_incidentreport_media_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
