# Generated by Django 4.2.4 on 2024-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreport', '0005_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
