# Generated by Django 4.2.4 on 2024-09-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(max_length=6),
        ),
    ]
