# Generated by Django 4.2.4 on 2024-09-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_verification_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
